language: python
python:
  - "3.6.5"

services:
  - postgres
  
install:
  - pip install -r requirements.txt
  
env:
  - TESTING = True

before_script:
  - psql -c 'create database SendItBagzie;' -U postgres

script:
  - pytest --cov
  - coverage
  - coverage3 report
  - coveralls 
after_success:
  - coveralls
