language: python
python:
  - "3.6.5"
install:
  - pip install -r requirements.txt
#Specify what command to run test
services:
  - postgres
env:
  global:
    - APP_SETTINGS='test_db'
script:
  - pytest --cov
  - coverage
  - coverage3 report
  - coveralls 
after_success:
  - coveralls